//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_PlayerDetails
    {
        public ref_PlayerDetails()
        {
            this.trn_ScoreCardDetails = new HashSet<trn_ScoreCardDetails>();
            this.trn_UserTeamDetails = new HashSet<trn_UserTeamDetails>();
        }
    
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> PlayerRoleId { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual ref_PlayerRole ref_PlayerRole { get; set; }
        public virtual ref_TeamDetails ref_TeamDetails { get; set; }
        public virtual ICollection<trn_ScoreCardDetails> trn_ScoreCardDetails { get; set; }
        public virtual ICollection<trn_UserTeamDetails> trn_UserTeamDetails { get; set; }
    }
}
