//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_TeamDetails
    {
        public ref_TeamDetails()
        {
            this.ref_PlayerDetails = new HashSet<ref_PlayerDetails>();
            this.ref_MatchDetails = new HashSet<ref_MatchDetails>();
            this.ref_MatchDetails1 = new HashSet<ref_MatchDetails>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
    
        public virtual ICollection<ref_PlayerDetails> ref_PlayerDetails { get; set; }
        public virtual ICollection<ref_MatchDetails> ref_MatchDetails { get; set; }
        public virtual ICollection<ref_MatchDetails> ref_MatchDetails1 { get; set; }
    }
}
