//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_MatchDetails
    {
        public ref_MatchDetails()
        {
            this.trn_ScoreCardDetails = new HashSet<trn_ScoreCardDetails>();
            this.trn_UserTeamDetails = new HashSet<trn_UserTeamDetails>();
        }
    
        public int MatchId { get; set; }
        public string Venue { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<System.TimeSpan> MatchTime { get; set; }
        public Nullable<int> FirstTeam { get; set; }
        public Nullable<int> SecondTeam { get; set; }
        public Nullable<int> IsCompleted { get; set; }
    
        public virtual ref_TeamDetails ref_TeamDetails { get; set; }
        public virtual ref_TeamDetails ref_TeamDetails1 { get; set; }
        public virtual ICollection<trn_ScoreCardDetails> trn_ScoreCardDetails { get; set; }
        public virtual ICollection<trn_UserTeamDetails> trn_UserTeamDetails { get; set; }
    }
}
