//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_UserDetails
    {
        public ref_UserDetails()
        {
            this.trn_UserTeamDetails = new HashSet<trn_UserTeamDetails>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ref_UserRole ref_UserRole { get; set; }
        public virtual ICollection<trn_UserTeamDetails> trn_UserTeamDetails { get; set; }
    }
}
