//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_ScoreCardDetails
    {
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> RunsScored { get; set; }
        public Nullable<int> FourCount { get; set; }
        public Nullable<int> SixCount { get; set; }
        public Nullable<int> RunOutorCatches { get; set; }
        public Nullable<int> WicketsTaken { get; set; }
        public Nullable<int> MaidenOvers { get; set; }
        public int OverId { get; set; }
    
        public virtual ref_PlayerDetails ref_PlayerDetails { get; set; }
        public virtual ref_MatchDetails ref_MatchDetails { get; set; }
    }
}
